export_languages: ["de_DE"]
append_commit_message: false
commit_message: 'New translations from Crowdin'
files:
  - source: /**/en_US.properties
    translation: /**/%locale_with_underscore%.properties
